// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARuhgANqEoFig-eEwljHyX3gvMfuP7fWk',
    appId: '1:938246746448:web:2c7e537f6d19116062bc55',
    messagingSenderId: '938246746448',
    projectId: 'appdev-finalexam-app',
    authDomain: 'appdev-finalexam-app.firebaseapp.com',
    storageBucket: 'appdev-finalexam-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDynScDb6cRLtQeDkiwTDnvge7PZMATvbk',
    appId: '1:938246746448:android:f779b0cb09fb2e5a62bc55',
    messagingSenderId: '938246746448',
    projectId: 'appdev-finalexam-app',
    storageBucket: 'appdev-finalexam-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKBCMuz7QkPgkX4EpC-TrnrqF8OX_qRLk',
    appId: '1:938246746448:ios:5482491eb1cd5c3462bc55',
    messagingSenderId: '938246746448',
    projectId: 'appdev-finalexam-app',
    storageBucket: 'appdev-finalexam-app.firebasestorage.app',
    iosBundleId: 'com.example.finalexamApp',
  );
}
